### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by dfloresgonz** [lob/lambda-pdftk-example#4]
Hello I get this error:

       /bin/sh: /var/task/bin/pdftk: Permission denied
       at ChildProcess.exithandler (child_process.js:294:12)
       at ChildProcess.emit (events.js:198:13)
       at maybeClose (internal/child_process.js:982:16)
       at Socket.stream.socket.on (internal/child_process.js:389:11)
       at Socket.emit (events.js:198:13)
       at Pipe._handle.close (net.js:607:12)
     cause:
      { Error: Command failed: pdftk './pdf1.pdf' './pdf2.pdf' cat output /tmp/tmp-808h0P0DOq5v1
      /bin/sh: /var/task/bin/pdftk: Permission denied

should I use chmod? does it matter if I have ubuntu?

**Comment by dfloresgonz** [comment]
Yes chmod resolved my issue.

**Comment by luis-17** [comment]
How is chmod going to solve the problem if it is a lambda? Where would you apply the chmod? its serverless arquitecture. Help me pls, Have same problem!!
